### ISSUE TITLE
OpenCV Streamer

### ISSUE THREAD

**Issue by aaravdave** [aaravdave/Lock-Video-Conferencing#3]
We need a good server to stream OpenCV data- under progress and very easy to receive, but needs a bit more work. PR if you have the solution.

**Comment by Infinite-Blue-1042** [comment]
I have a solution. Respond if you want to hear more about it

**Comment by aaravdave** [comment]
Yes, of course!

**Comment by Infinite-Blue-1042** [comment]
Ok, so you can setup your Raspberry Pi 3 B+ as a LAMP Web server, and get a camera module ( The cheapest out there are $15~ ), and then connect it. You can the pi as a server and the camera to get the video stream. You can also get a microphone module to for voice.

**Comment by aaravdave** [comment]
Nah. I want something using either an internet website socket or a real socket. Camera has to be built in.

**Comment by Infinite-Blue-1042** [comment]
Okay, how about later using the resist blue computer? I hear they are developing it and should come out by late 2021. That has a SIM card for unique user identification, and portable chip containing the receiver code, and a built in camera with a touchscreen display. They also have the option to store the chat history. It can run the chat program on it's OS

**Comment by aaravdave** [comment]
xD We're making the Resist Blue! I can orientate this towards a Resist Application if you want, but then I'll be using Fluent instead of Python.

**Comment by Infinite-Blue-1042** [comment]
Ok sure
